### ISSUE TITLE
requestMsg.indexOf is not function

### ISSUE THREAD

**Issue by jzos** [AlexanderMac/http-request-parser#1]
When I use the following trying to parse through a form post using Content-Type:text/html; charset=utf-8 to post to nodejs, I get the following.

app.post('/api/my-request', function (req, res) {

    var requestObj = parser.parse(req);
    console.log(requestObj);

}

it throws this:

<pre>TypeError: requestMsg.indexOf is not a function<br> &nbsp; &nbsp;at _parseRequestForLines (/Users/jaimemac/work/symamp/apps/prototype/node_modules/http-request-parser/lib/parser.js:48:49)<br> &nbsp; &nbsp;at Object.parse (/Users/jaimemac/work/symamp/apps/prototype/node_modules/http-request-parser/lib/parser.js:23:27)<br> &nbsp; &nbsp;at /Users/jaimemac/work/symamp/apps/prototype/api/index.js:112:29<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at textParser (/Users/jaimemac/work/symamp/apps/prototype/node_modules/body-parser/lib/types/text.js:78:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/Users/jaimemac/work/symamp/apps/prototype/node_modules/express/lib/router/index.js:275:10)</pre>
</body>
</html>

**Comment by AlexanderMac** [comment]
The goal of this library is parsing raw http request message, not node.js request object. To parse `req` object you need to use libraries like as `body-parser`, `cookie-parser`, etc.
