### ISSUE TITLE
InvalidRequestError

### ISSUE THREAD

**Issue by khsmaxim** [AlexanderMac/http-request-parser#2]
GET /USD_XRP HTTP/1.1
Host: 127.0.0.1:10081
Connection: keep-alive
Accept: */*
Origin: http://local.stock.com:7115
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Referer: http://local.stock.com:7115/test/socket-client.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9

D:\max\workspace\myproject\stockpush\solution\stockpush\node_modules\http-request-parser\lib\parser.js:50
    throw new InvalidRequestError(
    ^

**Comment by khsmaxim** [comment]
seems for Windows instead of "\n" can be "\r\n" in two places

var headersAndBodySeparator = '\r\n\r\n';

var paramValue = param.replace(paramMatch, '').trim('\r\n');

**Comment by AlexanderMac** [comment]
`parse` method now accepts `eol` parameter, `\n` by default.
